honeycombio/honeyaws

main.go

If there are more than one ELB worth of log files in the same S3 Prefix, honeyelb should not try upload every log file from every ELB each time that it tries to ingest logs for an ELB.

Be more selective grabbing logfiles

---

logbucket/logbucket.go
main.go
publisher/publisher.go

This is the first step towards having parsers for ALB, CloudFront, and maybe CloudTrail as well. The code for dealing with log buckets is split out and mostly ELB-specific info is contained in `main.go` (so that the other modules can be re-used). 
Signed-off-by: Nathan LeClaire <nathan@honeycomb.io>

Split components into several for re-use

---

publisher/publisher.go

Looking at sample rates in ELB datasets, they appear fixed. I think this is because the sample rate is being set on the `honeytail/event.Event` object and not passed through to the `libhoney.Event` object when it's created. This PR fixes that.

propogate sample rate set by the dynsampler to libhoney

---

cloudformation/dynamoDB.yml

Using this cloudformation template, a user can create the dynamoDB table necessary for high availability log ingestion. 
```
aws cloudformation create-stack --stack-name DynamoDBHoneyELB --template-body file://cloudformation/dynamoDB.yml
```

cloudformation template for creating dynamodb table

---

publisher/request_shaper.go

Turns out that though we do URL shaping in `honeyaws`, we don't actually do anything with any variables that might have been specified in a routes listing.  We should add those as fields, if they exist.

add urlshaper parsed fields if they exist

---

build-pkg.sh
preinstall
service/honeyalb.service
service/honeyalb.upstart
service/honeycloudtrail.service
service/honeycloudtrail.upstart

This updates `honeycloudtrail` and `honeyalb` to be bundled in the deb and RPM packages we distribute.

Update packaging scripts to include new binaries

---

cloudformation/dynamoDB.yml

Fixes [issue 42](https://github.com/honeycombio/honeyaws/issues/42). 
The Cloudformation stack we were using created a partition key that's hash was the S3Object and range the time stamp. As a result, when we attempted to do `attribute_not_exists(S3Object)`, and not specifying the `range` of the partition key as well - it would return true every time. As a result of returning true, duplicates were being sent to Honeycomb. 
Luckily, you can shove arbitrary keys into DynamoDB - they don't need to be specified in the schema. Deleting the range key was sufficient to let `attribute_not_exists(HASH)` actually work! 
```
$ ./honeyelb --writekey=<> --dataset="susan-honeyelb-test" ingest shepherd-dogfood-lb --highavail
INFO[2018-04-04T16:49:39-04:00] High availability enabled - using DynamoDB …
```

deleting timestamp as range key

---

options/options.go

Found myself wanting the same `-k` and `-d` flags as on honeytail.

Add short flag versions to honeyaws

---

publisher/cloudtrail.go

Without the request parameters, a lot of context is missing for certain events. For example, for SSM:GetParameter, I want to know what parameter was requested. For S3:GetObject, knowing the bucket/key that was requested is helpful.

[honeycloudtrail] include request parameters in cloudtrail events

---

cloudformation/dynamoDB.yml
logbucket/logbucket.go
publisher/publisher.go
state/state.go

Currently an issue exists within the HA implementation where if multiple
agents are started concurrently, they don't have time to set the object
their downloading to "Processed". By changing the ordering of when we
set an object to processed - before it's downloaded, other threads will
be able to see that the object is being worked on or is already
published.
The caveat here is that if an object fails to publish or download
correctly, it will already be set to "processed". The trade off is
either publishing duplicates, or losing a log or two.

Change ordering of processed

---

cmd/honeycloudfront/main.go

Looks like the existing url is probably copypasta? :)

Swap in url to CloudFront in error message

---

publisher/alb_test.go
publisher/publisher.go

This changes how `duration_ms` is computed for ALB logs. According to the docs, `request_creation_time` is the time when the load balancer first gets the request. `timestamp` is poorly defined, but appears to correspond to when the event is actually finished. Therefor, comparing the two should allow us to see the actual transmission duration as observed by the client. I confirmed that a very long (multi-minute) download I performed does in fact have a multi-minute duration using this calculation.
This could be viewed as a breaking change. If we don't want that, I could put this duration in a different field; however, I think this number is more correct, and we still have the `response_processing_time` field.
Also add a test for ALB logs, and add parenthesis to a couple of fields which …

compute wallclock duration for ALB events

---

options/options.go
publisher/alb_test.go
publisher/publisher.go
publisher/publisher_test.go

When run in edge mode, honeyalb and honeyelb will ignore the parent_id segment of Amazon trace headers. This prevents requests from the public internet containing amazon headers from resulting in broken traces (missing root spans).

Add support for edge mode

---

.circleci/config.yml

We created a new context in Circle for public repos (Honeycomb Secrets for Public Repos), which is identical to the Honeycomb Secrets, with the exception of the Github token, which has more restrictive privileges (only public repos).
This will continue to allow builds to publish Github releases in the public repos, without exposing access to private repos.

User public ENV context in circleci

---

.circleci/config.yml

It seems that all jobs need at least a filter to be run on tags.

Adding filters to build job

---

Dockerfile

Because libhoney-go requires the use of Go modules, create a dummy go.mod in the dockerfile before calling go get.

Force dockerfile to use go modules

---

.circleci/config.yml

- Typo on #159 
- rename `build_docker.sh` to `build-docker.sh`

Fix typo in publish_docker job for build-docker script

---

go.mod
go.sum

Updates libhoney-go dependency to latest.
- update libhoney-go to v1.15.6 in go.mod/sum

Bump libhoney-go

---

.circleci/config.yml
go.mod

Bumps go to v1.17
- bumps go to v1.17 in go.mod and images used in CircleCI

Bump go version to 1.17

---

README.md
terraform/dynamodb_table.tf

The readme instructions are not up to date according to these two issues:
https://github.com/honeycombio/honeyaws/issues/42
https://github.com/honeycombio/honeyaws/pull/44
Also add a terraform snippet for the dynamo db table

Fix readme instructions and add terraform snippet

---

.circleci/config.yml
go.mod

Update go to latest version.
- Updates go to v1.18 both in go.mod and circle CI image used to build binaries

Update go to 1.18

---

CHANGELOG.md

Fixes OpenSSL CVE by rebuilding on a new container.

Prep v1.4.4

---

.circleci/config.yml

- docker/publish job [failed](https://app.circleci.com/pipelines/github/honeycombio/honeyaws/365/workflows/332e10df-ebb5-43e9-9dda-b00f7c2ae4aa/jobs/678) in ci with "This job was rejected because the image is unavailable"
- the docker orb version we were trying to use was really old --> bring it up to speed
- I tried to dry run the job, but too many steps rely on a tag in the specific format 😩 
- the job did at least [start to run](https://app.circleci.com/pipelines/github/honeycombio/honeyaws/367/workflows/61174422-74ad-4bc1-9a1c-6e2c42f98648/jobs/685) so I'm fairly confident that it will work with a real release tag

maint: update docker orb version

---

.github/workflows/gh-issue-to-asana.yml
.github/workflows/gh-pr-to-asana.yml

**Which problem is this PR solving?**
https://app.asana.com/0/1198607545155957/1203451723732961/f
**Short description of the changes**
This adds 2 Github Actions to the repo to run on issue creation and PR opens/reopens. All issues become tasks and PRs become tasks if they don't have an Asana link in the description. These tasks go to our team board in the Inbox column.

ci: send Github issues and PRs to Asana 

---

.github/workflows/gh-pr-to-asana.yml

This change updates the PR to Asana workflow to run on pull_request_target events so it can work on PRs from forks. This should subvert the need to approve the workflow to run and allow the workflow to access the necessary secrets.

ci: update workflow to work for pull_request_target

---

publisher/alb_test.go
publisher/publisher.go

See AWS docs for more info on these new fields:
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-log-entry-syntax
- Closes honeycombio/honeyaws#253
Adds support for parsing additional fields in the ALB logs
Updated the tests, and we've run this build against our production ALB logs.

feat: Add support for missing ALB fields

---

.circleci/config.yml

We had both `docker/publish` and `publish_docker` in our build config. `docker/publish` seems to fail every time (presumably because it's using old secrets that have been removed) so let's just clean it up. `publish_docker` still gets our artifacts to DockerHub.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205014262861190

ci: remove duplicate docker publish
