- Godeps/Godeps.json
- main.go
- publisher/publisher.go
- vendor/github.com/honeycombio/dynsampler-go/LICENSE
- vendor/github.com/honeycombio/dynsampler-go/NOTICE
- vendor/github.com/honeycombio/dynsampler-go/README.md
- vendor/github.com/honeycombio/dynsampler-go/avgsamplerate.go
- vendor/github.com/honeycombio/dynsampler-go/avgsamplewithmin.go
- vendor/github.com/honeycombio/dynsampler-go/doc.go
- vendor/github.com/honeycombio/dynsampler-go/dynsampler.go
- vendor/github.com/honeycombio/dynsampler-go/onlyonce.go
- vendor/github.com/honeycombio/dynsampler-go/perkeythroughput.go
- vendor/github.com/honeycombio/dynsampler-go/static.go
- vendor/github.com/honeycombio/dynsampler-go/totalthroughput.go
FYI @maplebed 
nitpicks:
- `select` for ticker seems unneeded if only selecting on one value
- variables should be `camelCase`
- prefer to call `go` on functions with names (to avoid passing in to func literal via implicit scoping -- pass `chan` etc. only as needed -- might want to pass in the sampler too and pull the method off the `struct`)
- update deps
thanks for the original commits!
> Add dynamic sampling

- main.go
I couldn't run the tool as it was; I got errors like "Must specify userName when calling with non-User credentials". This seems to be a recommended way of getting user identity.
> Move from IAM to STS API for grabbing user identity

- main.go
This will help alleviate a memory usage issue since each LB goroutine was sending its own events to `libhoney` concurrently, causing memory inflation. There might still be some memory usage issues (e.g., bucket object downloads might need to be similarly bottlenecked through one `downloader` which will only download N at once) but this is one step towards reducing memory usage.
Thanks @JohnLooney for reporting!
cc @maplebed
> Use only one publisher for all LBs

- publisher/publisher.go
w bonus comment
it's still a mystery that `rate` would be <=0, that shouldn't happen based on what i'm seeing in the `dynsampler` code, but this should workaround until we figure out the issue in the interim
Signed-off-by: Nathan LeClaire <nathan@honeycomb.io>
> Add randint check

- options/options.go
- publisher/publisher.go
- Always use sample rate of 1 out of the box
- Add elb name to sampler field to make sampling rate per-ELB
cc @maplebed
> Add updates to sampling logic

- logbucket/logbucket.go
- main.go
Added some debug information as well.
> Fix extraneous prefix slash issue

- publisher/publisher.go
Right now we're passing the `-1`s that aws puts into the log into honeycomb.  This has a negative (hah) effect on all calculations over those times.  `AVG(backend_processing_time)` will be pulled down, `SUM()` might appear zero (or negative) for a bucket with enough -1s, etc.
-1 is used to represent "no data", but in honeycomb we support missing data, and filtering it via `exists`/`does-not-exist`
> drop negative times that aws puts into the log to represent no data

- Dockerfile
Sometimes I get confused with all the things that start with "Cloud"
Signed-off-by: Nathan LeClaire <nathan@honeycomb.io>
> Fix putting wrong AWS service in Dockerfile

- cmd/honeycloudfront/main.go
- cmd/honeyelb/main.go
Noticed these seem a bit erroneous and redundant
> Fix formatting error in main.go

- .travis.yml
Enables automatic publishing of docker images after successful builds on master.
> Add config for docker builds/publishing

- publisher/publisher.go
- publisher/publisher_test.go
Fixes https://github.com/honeycombio/honeyaws/issues/35
> Add 'error' field when -1 processing time occurs

- cmd/honeyalb/main.go
- cmd/honeycloudfront/main.go
- cmd/honeycloudtrail/main.go
- cmd/honeyelb/main.go
> Remove unreachable os.Exits

- publisher/publisher.go
- publisher/publisher_test.go
Addresses panics documented here: https://app.asana.com/0/530133862194001/1155652454881545
> additional safety checking in addTraceData

- .circleci/config.yml
Build binaries as well as deb and rpm packages and upload them to S3.
> Build amd64, arm64 binaries for linux and darwin.

- CHANGELOG.md
- RELEASE.md
Prepares the v1.4.2 release.
- add changelog entry
- add release documentation
> Prepare v1.4.2 release

- CHANGELOG.md
Patch release accumulating changes.
Fixes #185.
> Prep for 1.4.3

- go.mod
- go.sum
> bump honeytail from 1.8.1 to 1.8.2

- CHANGELOG.md
> prepare 1.4.5 release

- .github/workflows/gh-issue-to-asana.yml
- .github/workflows/gh-pr-to-asana.yml
We agreed in Slack that we need a bit more info in these Asana tasks to make them useful. I have added the repo name to the task title and a link to the issue or PR at the end of the task body to meet our needs.
> ci: add repo name and repo link to asana task 

- .github/workflows/gh-issue-to-asana.yml
- .github/workflows/gh-pr-to-asana.yml
Includes tags to allow for easier categorization of the Asana cards created for the maintainer team to track the work
> chore: include tags for the asana cards created
